##### an MQTT switch running Tasmota firmware

- platform: mqtt
  name: "Heater 1"
  state_topic: "stat/heaterswitch/POWER1"
  command_topic: "cmnd/heaterswitch/POWER1"
  availability_topic: "tele/heaterswitch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Heater 2"
  state_topic: "stat/heaterswitch/POWER2"
  command_topic: "cmnd/heaterswitch/POWER2"
  availability_topic: "tele/heaterswitch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false

- platform: mqtt
  name: "Main pump"
  state_topic: "stat/heaterswitch/POWER3"
  command_topic: "cmnd/heaterswitch/POWER3"
  availability_topic: "tele/heaterswitch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
